### PR TITLE
feature: Generate random pin

### PR DESCRIPTION
**Pull request by LindaNayeli104**

### CODE REVIEW

**Review by sderacy — APPROVED** [review]
The js and HTML file LGTM, but I am somewhat concerned about the css file since I modified it too. The CSS file looks good though.

**Comment by sderacy** [comment]
oh sorry I wasn't asking for you to change it! I was just saying I'm not sure if there'll be an issue here. It'd probably be a good idea to ask Alison when we see her

**Comment by LindaNayeli104** [comment]
> 
> 
> oh sorry I wasn't asking for you to change it! I was just saying I'm not sure if there'll be an issue here. It'd probably be a good idea to ask Alison when we see her

Don't apologize haha. I also think that there may be conflicts If we put everything in one css file. I think it's a good idea to separate the css code to avoid conflicts and also to make it easier to read, I'll do that while we ask Alison.

**Comment by alisonberkowitz** [comment]
> > oh sorry I wasn't asking for you to change it! I was just saying I'm not sure if there'll be an issue here. It'd probably be a good idea to ask Alison when we see her
> 
> Don't apologize haha. I also think that there may be conflicts If we put everything in one css file. I think it's a good idea to separate the css code to avoid conflicts and also to make it easier to read, I'll do that while we ask Alison.

I think breaking the stylesheets out into specific files per feature is a great idea :) For both the reasons you mention here.

**Review by alisonberkowitz — APPROVED** [review]

**Review by orellanadani12 — APPROVED** [review]
Wow! That's a lot of changes lol. Good job!

**Review by oscarfermor — APPROVED** [review]

**Pull request merged**
